apiVersion: apps/v1
kind: Deployment
metadata:
    name: employee-depl
spec:
    replicas: 3
    selector:
        matchLabels:
            app: employeeservice
    template:
       metadata:
         labels:
           app: employeeservice
    spec:
        containers:
             - name: employeeservice
               image: employeeservice:latest
               ports:
                - containerPort: 80    