apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beautysalon-employees-api
  template:
    metadata:
      labels:
        app: beautysalon-employees-api
    spec:
      containers:
        - name: beautysalon-employees-api
          image: woogie42/beautysalon.employees.api:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: productsbackend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: beautysalon-employees-api