name: deployment Employees Service

on:
  push:
    branches: 
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/beautysalon.employees.api:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/beautysalon.employees.api:${{ github.sha }}

      - name: Update Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: kubectl set image deployment/employees-deployment beautysalon-employees-api=${{ secrets.DOCKER_USERNAME }}/beautysalon.employees.api:${{ github.sha }} -n default